version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: analytics_postgres
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - analytics_network

  redis:
    image: redis:7-alpine
    container_name: analytics_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - analytics_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: analytics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@analytics.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - analytics_network

volumes:
  postgres_data:
  redis_data:

networks:
  analytics_network:
    driver: bridge